- hosts: localhost
  
  vars:
    docker_container: nginx
    docker_image: bp_test_nginx
    docker_tag: latest

  tasks:
  - name: install docker-py
    pip:
      name: docker-py
      state: present

  - name: install docker
    yum:
      name: docker
      state: latest

  - name: start docker
    service:
      name: docker
      state: started

  - name: build container
    docker_image:
      path: /vagrant/Docker
      name: "{{ docker_image }}"
      tag: "{{ docker_tag }}"
      push: no

  - name: start container
    docker_container:
      name: "{{ docker_container }}"
      image: "{{ docker_image }}"
      state: started
      restart: yes 
      ports:
        - "8080:80"

  - name: get static content from localhost
    uri:     
      url: http://localhost:8080     
      return_content: yes   
      register: page  - 

  - name: check page content   
    fail:   
    when: "'Hello World!E' not in page.content"
